#!/usr/bin/env bash
# this script loops from 1 to 10 and displays "bad luck for 4th loop, "good luck" for 8th loop, "best school" foor other iterations

i=0

while ((i < 10))
do
	((i++))
	if ((i == 4))
	then
		echo "bad luck"
	elif ((i == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
