#!/usr/bin/env bash
# This script displays the time for 12 hours and 59 minutes

i=0
i2=1

while ((i < 13))
do
	echo "Hour: $1"
	while ((i2 < 60))
	do
		echo "$i2"
		let i2++
	done
	let i2=1
	let i++
done

